[otlp]
# valid values: http/protobuf or grpc
protocol = "grpc"
endpoint = ""

[log]
# valid values: stdout, file
writer = "stdout"
# valid values: trace, debug, info, warn, error, off
level = "info"

[log.file]
# valid values: minutely, hourly, daily, weekly, never
rotation = "daily"
max_log_files = 5
directory = "/tmp"
filename = "metrics_exporter.log"
