[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
lexical = "7.0.5"
opentelemetry = { version = "0.32.0", features = ["metrics"] }
parking_lot = "0.12.5"
serde = "1.0.229"
smallvec = "1.15"
thiserror = "2.0.20"
time = "0.3.55"
tracing = "0.1.44"

[package]
name = "metrics_exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
config = { version = "0.15.25", default-features = false, features = ["toml"] }
core_affinity = "0.8.3"
ctrlc = { version = "3.5.2", features = ["termination"] }
linux-metrics = { path = "./crates/linux-metrics" }
metrics-framework = { path = "./crates/metrics-framework" }
opentelemetry = { workspace = true }
opentelemetry_sdk = { version = "0.32.1", features = ["metrics"] }
opentelemetry-otlp = { version = "0.32.0", features = [
    "metrics",
    "grpc-tonic",
    "http-proto",
    "reqwest-blocking-client",
] }
parking_lot = { workspace = true }
procfs = { path = "./crates/procfs" }
serde = { workspace = true, features = ["derive"] }
time = { workspace = true, features = ["macros"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
tonic = "0.14.6"
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "local-time",
] }

[profile.dev]
opt-level = 0
debug = "full"
panic = "abort"

[profile.release]
opt-level = 2
debug = "none"
panic = "abort"
