[runtime]
worker_threads = 2

[otlp]
# valid values: http/protobuf or grpc
protocol = "http/protobuf"
endpoint = "http://127.0.0.1:8428/opentelemetry/v1/metrics"
interval_secs = 1
timeout = 5

[metrics.host]
enable = true
interval_secs = 1

[metrics.host.cpu]
enable = true
per_core = false

[metrics.host.mem]
enable = true

[metrics.host.process]
enable = true
# comms = []
thread = false

[metrics.host.net]
enable = true
# ifaces = []

[metrics.host.disk]
enable = true
exclude_devices = ["dm-.*", "loop\\d+", "nvme0n1p\\d+", "sda\\d+", "sdb\\d+", "sdc\\d+", "sr\\d+"]

[log]
# valid values: stdout, file
writer = "stdout"
# valid values: trace, debug, info, warn, error, off
level = "info"

[log.file]
# valid values: minutely, hourly, daily, weekly, never
rotation = "daily"
max_log_files = 5
directory = "/tmp"
filename = "metrics_exporter.log"
