apiVersion: 1

datasources:
  - name: victoriametrics-metrics-datasource
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://localhost:8428
    orgId: 1
    isDefault: true
    jsonData:
      pdcInjected: false
      timeout: 10
      httpMethod: "POST"
    withCredentials: false
    editable: true
